namespace WinRive
{
    [default_interface]
    runtimeclass ViewModelInstanceProperty
    {
        ViewModelInstanceProperty();
        
        // Basic info
        String Name { get; };
        ViewModelPropertyType Type { get; };
        Int32 Index { get; };
        
        // Value access - use Object to support different types
        Object Value { get; set; };
        
        // Type-safe accessors
        String StringValue { get; set; };
        Double NumberValue { get; set; };
        Boolean BooleanValue { get; set; };
        UInt32 ColorValue { get; set; };
        Int32 EnumValue { get; set; };
        
        // Trigger support
        void Fire();
        
        // Validation
        Boolean IsValid();
        
        // Events
        event Windows.Foundation.TypedEventHandler<ViewModelInstanceProperty, Object> ValueChanged;
    }
}
